- block:
  - name: create home base dir
    file:
      path: "{{ user.home | dirname }}"
      state: directory
      mode: 0755
  - name: create group
    group:
      name: "{{ user.group.split(',')[0] }}"
      gid: "{{ user.gid|default(omit) }}"
  - name: create user
    user:
      name: "{{ user.user }}"
      group: "{{ user.group.split(',')[0] }}"
      groups: "{{ user.group }}"
      uid: "{{ user.uid|default(omit) }}"
      password: "{{ user.password|default(omit) }}"
      home: "{{ user.home|default(omit) }}"

  - name: copy ssh-keys
    authorized_key:
      user: "{{ user.user }}"
      state: present
      key: "{{ lookup('file', key) }}"
    loop: "{{ lookup('fileglob', FABSIBLE_CWD|default('..')+'/files/ssh-keys/'+user.user+'/*', wantlist=True) }}"
    loop_control:
      loop_var: key

  ignore_errors: "{{ ignore_erros|default(False) }}"
  ignore_unreachable: "{{ ignore_unreachable|default(False) }}"
  become: True
