- block:
  - name: create home base dir
    file:
      path: "{{user.home | dirname}}"
      state: directory
  - name: create group
    group:
      name: "{{user.group.split(',')[0]}}"
  - name: create user
    user:
      name: "{{user.user}}"
      groups: "{{user.group}}"
      password: "{{user.password|default(omit)}}"
      home: "{{user.home|default(omit)}}"

  - name: copy ssh-keys
    authorized_key:
      user: "{{user.user}}"
      state: present
      key: "{{lookup('file', key)}}"
    loop: "{{lookup('fileglob', FABSIBLE_CWD|default('..')+'/files/ssh-keys/'+user.user+'/*', wantlist=True)}}"
    loop_control:
      loop_var: key

  become: True
